project:
  type: website
  output-dir: _site

website:
  title: "Oliver Hatley - Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd#projects
        text: Projects
      - href: index.qmd#experience
        text: Experience
      - href: index.qmd#contact
        text: Contact
        
format:
  html:
    theme: theme.scss
    css: styles.css
    toc: false